Update to PCRE v10.10

diff --git a/src/PCRE/RunTest b/src/PCRE/RunTest
--- a/src/PCRE/RunTest
+++ b/src/PCRE/RunTest
@@ -65,6 +65,7 @@ title15="Test 15: JIT-specific features when JIT is not available"
 title16="Test 16: JIT-specific features when JIT is available"
 title17="Test 17: Tests of the POSIX interface, excluding UTF/UCP"
 title18="Test 18: Tests of the POSIX interface with UTF/UCP"
+title19="Test 19: Serialization tests"
 maxtest=18
 
 if [ $# -eq 1 -a "$1" = "list" ]; then
@@ -87,6 +88,7 @@ if [ $# -eq 1 -a "$1" = "list" ]; then
   echo $title16
   echo $title17
   echo $title18
+  echo $title19
   exit 0
 fi
 
@@ -207,6 +209,7 @@ do15=no
 do16=no
 do17=no
 do18=no
+do19=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
@@ -229,6 +232,7 @@ while [ $# -gt 0 ] ; do
    16) do16=yes;;
    17) do17=yes;;
    18) do18=yes;;
+   19) do19=yes;;
    -8) arg8=yes;;
   -16) arg16=yes;;
   -32) arg32=yes;;
@@ -364,7 +368,7 @@ if [ $do0  = no -a $do1  = no -a $do2  = no -a $do3  = no -a \
      $do4  = no -a $do5  = no -a $do6  = no -a $do7  = no -a \
      $do8  = no -a $do9  = no -a $do10 = no -a $do11 = no -a \
      $do12 = no -a $do13 = no -a $do14 = no -a $do15 = no -a \
-     $do16 = no -a $do17 = no -a $do18 = no \
+     $do16 = no -a $do17 = no -a $do18 = no -a $do19 = no \
    ]; then
   do0=yes
   do1=yes
@@ -385,6 +389,7 @@ if [ $do0  = no -a $do1  = no -a $do2  = no -a $do3  = no -a \
   do16=yes
   do17=yes
   do18=yes
+  do19=yes
 fi
 
 # Handle any explicit skips at this stage, so that an argument list may consist
@@ -454,45 +459,47 @@ for bmode in "$test8" "$test16" "$test32"; do
     done
   fi
 
-  # Locale-specific tests, provided that either the "fr_FR" or the "french"
-  # locale is available. The former is the Unix-like standard; the latter is
-  # for Windows. Another possibility is "fr". Unfortunately, different versions
-  # of the French locale give different outputs for some items. This test passes
-  # if the output matches any one of the alternative output files.
+  # Locale-specific tests, provided that either the "fr_FR", "fr_CA", "french"
+  # or "fr" locale is available. The first two are Unix-like standards; the
+  # last two are for Windows. Unfortunately, different versions of the French
+  # locale give different outputs for some items. This test passes if the
+  # output matches any one of the alternative output files.
 
   if [ $do3 = yes ] ; then
-    locale -a | grep '^fr_FR$' >/dev/null
-    if [ $? -eq 0 ] ; then
-      locale=fr_FR
-      infile=$testdata/testinput3
-      outfile=$testdata/testoutput3
-      outfile2=$testdata/testoutput3A
-      outfile3=$testdata/testoutput3B
-    else
-      infile=test3input
-      outfile=test3output
-      outfile2=test3outputA
-      outfile3=test3outputB
-      locale -a | grep '^french$' >/dev/null
+    locale=
+
+    # In some environments locales that are listed by the "locale -a"
+    # command do not seem to work with setlocale(). Therefore, we do
+    # a preliminary test to see if pcre2test can set one before going
+    # on to use it.
+
+    for loc in 'fr_FR' 'french' 'fr' 'fr_CA'; do
+      locale -a | grep "^$loc\$" >/dev/null
       if [ $? -eq 0 ] ; then
-        locale=french
-        sed 's/fr_FR/french/' $testdata/testinput3 >test3input
-        sed 's/fr_FR/french/' $testdata/testoutput3 >test3output
-        sed 's/fr_FR/french/' $testdata/testoutput3A >test3outputA
-        sed 's/fr_FR/french/' $testdata/testoutput3B >test3outputB
-      else
-        locale -a | grep '^fr$' >/dev/null
-        if [ $? -eq 0 ] ; then
-          locale=fr
-          sed 's/fr_FR/fr/' $testdata/intestinput3 >test3input
-          sed 's/fr_FR/fr/' $testdata/intestoutput3 >test3output
-          sed 's/fr_FR/fr/' $testdata/intestoutput3A >test3outputA
-          sed 's/fr_FR/fr/' $testdata/intestoutput3B >test3outputB
-        else
-          locale=
+        echo "/a/locale=$loc" | \
+          $sim $valgrind ./pcre2test -q $bmode | \
+            grep "Failed to set locale" >/dev/null
+        if [ $? -ne 0 ] ; then
+          locale=$loc
+          if [ "$locale" = "fr_FR" ] ; then
+            infile=$testdata/testinput3
+            outfile=$testdata/testoutput3
+            outfile2=$testdata/testoutput3A
+            outfile3=$testdata/testoutput3B
+          else
+            infile=test3input
+            outfile=test3output
+            outfile2=test3outputA
+            outfile3=test3outputB
+            sed "s/fr_FR/$loc/" $testdata/testinput3 >test3input
+            sed "s/fr_FR/$loc/" $testdata/testoutput3 >test3output
+            sed "s/fr_FR/$loc/" $testdata/testoutput3A >test3outputA
+            sed "s/fr_FR/$loc/" $testdata/testoutput3B >test3outputB
+          fi
+          break
         fi
       fi
-    fi
+    done
 
     if [ "$locale" != "" ] ; then
       echo $title3 "(using '$locale' locale)"
@@ -519,9 +526,9 @@ for bmode in "$test8" "$test16" "$test32"; do
         fi
       done
     else
-      echo "Cannot test locale-specific features - none of the 'fr_FR', 'fr' or"
-      echo "'french' locales exist, or the \"locale\" command is not available"
-      echo "to check for them."
+      echo "Cannot test locale-specific features - none of the 'fr_FR', 'fr_CA',"
+      echo "'fr' or 'french' locales can be set, or the \"locale\" command is"
+      echo "not available to check for them."
       echo " "
     fi
   fi
@@ -721,10 +728,18 @@ for bmode in "$test8" "$test16" "$test32"; do
     fi
   fi
 
+  # Serialization tests
+
+  if [ $do19 = yes ] ; then
+    echo $title19
+    $sim $valgrind ./pcre2test -q $bmode $testdata/testinput19 testtry
+    checkresult $? 19 ""
+  fi
+
 # End of loop for 8/16/32-bit tests
 done
 
 # Clean up local working files
-rm -f testSinput test3input test3output test3outputA test3outputB teststdout testtry
+rm -f testSinput test3input testsaved1 testsaved2 test3output test3outputA test3outputB teststdout testtry
 
 # End
